cases = {
	"hourly": {
		"keywords": ["pm", "am", "hour", "hourly", "hours"], 
		"action": function(input){
			location = input.location;
			return "hourly message for " + location;
		}
	},
	"daily": {
		"keywords": ["tomorrow", "week", "days", "day"],
		"action": function(input){
			location = input.location;
			return "daily message for " + location;
		}
	},
	"DEFAULT": {
		"keywords": [],
		"action": function(input){
			return "Sorry, I didn't catch that";
		}
	}
}

exports.loadCases = function (){return cases}

// all_weather_conditions
// [
// 		"sunny",
// 		"cloudy",
// 		"windy",
// 		"rainy",
// 		"stormy",
// 		"foggy",
// 		"snowy",
// 		"lightning",
// 		"hail",
// 		"tornado",
// 		"hurricane",
// 		"flood",
// 		"tsunami",
// 		"forest",
// 		"fire",
// 		"rainbow",
// 		"hot",
// 		"cold"
// 	]

activities = {
    "Trekking": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Wildlife safari": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Snorkeling": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Angling/fly fishing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Gliding": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Camel safari": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Amusement park": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Indigenous culture": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Rock climbing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Camping": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Scuba diving": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Canyoning": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Ballooning": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Desert Jeep safari": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Safari park": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Mountain biking": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Birdwatching": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Parasailing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Whitewater rafting": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Flying": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Sandboarding": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Off-leash dog park": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Metal detecting": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Motorbike expedition": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Elephant safari": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Sport fishing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Water sports": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Paramotoring": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Bungee jumping": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Benchmarking": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Skiing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Tree climbing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Windsurfing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Kayaking": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Skydiving": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Picnicking": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Sightseeing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Snowboarding": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Adventure park": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Canoeing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Paragliding": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Corn maze": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Snowshoeing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Mushroom hunting": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Clam digging": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Waterskiing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Wingsuit flying": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Ice climbing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Orienteering": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Running": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Jetskiing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Mountain climbing": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "ATV riding": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Swimming": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Paintball": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    },
    "Skyrunning": {
        "temp_range_low": 60,
        "temp_range_high": 83,
        "agnostic_weather_conditions": {
            "sunny": false,
            "cloudy": false,
            "windy": false,
            "rainy": false,
            "stormy": false,
            "foggy": false,
            "snowy": true,
            "lightning": true,
            "hail": true,
            "tornado": true,
            "hurricane": true,
            "flood": true,
            "tsunami": true,
            "fire": true,
            "rainbow": false,
            "hot": false,
            "cold": true
        }
    }
}

exports.loadActivities = function(){return activities}